modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/ShadowKing21228/ShadowConfig/issues"
license = "All Rights Reserved"

[[mods]]
modId = "shadowconfig"
version = "${version}"
displayName = "Shadow Config"
authors = "ShadowKing21"
description = '''
Extensible configuration library for mods, designed to simplify config management with many functions and multiple file extensions
'''
logoFile = "assets/shadowconfig/icon.png"

[[dependencies.shadowconfig]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shadowconfig]]
modId = "minecraft"
type = "required"
versionRange = "[1.21, 1.21.1)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "shadowconfig.mixins.json"
